{ config, pkgs, lib, ... }:
{
  # Enable hardware sensors
  hardware.sensor.iio.enable = lib.mkDefault true;

  # Enable lm_sensors program (automatically loads kernel modules and makes commands available)
  programs.lm_sensors.enable = lib.mkDefault true;

  # Add fancontrol package
  environment.systemPackages = with pkgs; [
    fancontrol
  ];

  # Enable fancontrol service
  # Note: After first rebuild, run:
  # 1. sudo sensors-detect (to detect sensors) - answer yes to all prompts
  # 2. sudo pwmconfig (to configure fan control) - follow interactive setup
  # 3. sudo systemctl enable --now fancontrol (to start the service)
  services.fancontrol = {
    enable = lib.mkDefault true;
    # Configuration file will be generated by pwmconfig
    # Default location: /etc/fancontrol
    # The service will read from /etc/fancontrol automatically
  };

  # Add activation script to help users set up fancontrol
  system.activationScripts.fancontrol-setup = lib.mkAfter ''
    if [ ! -f /etc/fancontrol ]; then
      echo ""
      echo "=== Fan Control Setup ==="
      echo "To set up fan control, run the following commands:"
      echo "  1. sudo sensors-detect (answer yes to all prompts)"
      echo "  2. sudo pwmconfig (follow the interactive setup)"
      echo "  3. sudo systemctl enable --now fancontrol"
      echo "========================="
      echo ""
    fi
  '';
}
