[config]
version_check = false


[templates.niri]
input_path = '~/.config/niku/Color-Generator/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/colors/niri-colors.kdl'
post_hook = 'niri msg action load-config-file' # Not Important but given so everything goes smoothly.


[templates.hyprlock]
input_path = '~/.config/niku/Color-Generator/matugen/templates/hyprlock-color.conf'
output_path = '~/.config/niku/configs/hypr/colors/hyprlock-color.conf'


[templates.btop]
input_path = '~/.config/niku/Color-Generator/matugen/templates/btop-colors.theme'
output_path = '~/.config/btop/themes/btop-colors.theme'


[templates.rofi]
input_path = '~/.config/niku/Color-Generator/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'


[templates.waybar]
input_path = '~/.config/niku/Color-Generator/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors/colors.css'
post_hook = "pkill -SIGUSR2 waybar & swaync-client -rs" # This command reloads css. Swaync uses waybar colors


[templates.cava]
input_path = '~/.config/niku/Color-Generator/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/config'
post_hook = "pkill -USR1 cava"


[templates.kwybar]
input_path = '~/.config/niku/Color-Generator/matugen/templates/kwybars-colors.toml'
output_path = '~/.config/kwybars/colors.toml'


[templates.kitty]
input_path = '~/.config/niku/Color-Generator/matugen/templates/terminal/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -USR1 kitty'

[templates.swaylock]
input_path = '~/.config/niku/Color-Generator/matugen/templates/swaylock'
output_path = '~/.config/swaylock/config'

[templates.gtk3]
input_path = '~/.config/niku/Color-Generator/matugen/templates/gtk3.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""'


[templates.gtk4]
input_path = '~/.config/niku/Color-Generator/matugen/templates/gtk4.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = 'pkill -f gtk'


[templates.yazi]
input_path = '~/.config/niku/Color-Generator/matugen/templates/yazi-colors.toml'
output_path = '~/.config/yazi/flavors/niku.toml'


[templates.spicetify]
input_path = '~/.config/niku/Color-Generator/matugen/templates/spicetify.ini'
output_path = '~/.config/spicetify/Themes/niku/color.ini'
# post_hook = '~/.config/niku/Color-Generator/matugen/scripts/spice.sh'


# [templates.obs-studio]
# input_path = '~/.config/niku/Color-Generator/matugen/templates/obs-studio'
# output_path = '~/.config/obs-studio/themes/niku.'
