color0 #181210
color1 #ffb4ab
color2 #ffb692
color3 #e6beac
color4 #d0c890
color5 #ffb692
color6 #e6beac
color7 #ede0db
color8 #a08d85
color9 #ffb4ab
color10 #ffb692
color11 #e6beac
color12 #d0c890
color13 #ffb692
color14 #e6beac
color15 #ede0db

cursor                #ede0db
cursor_text_color     #181210
background            #181210
foreground            #ede0db
selection_foreground  #d7c2b9
selection_background  #52443d
active_border_color   #ffb692
inactive_border_color #52443d
url_color             #ffb692
