# Image Path
$image = /home/levi/Pictures/Wallpapers/cat-mocha-peach_6.jpg

# An alpha background
$surface_alpha = rgba(1812104d)

# All Colors
  $background = rgba(181210ff)
  $error = rgba(ffb4abff)
  $error_container = rgba(93000aff)
  $inverse_on_surface = rgba(362f2cff)
  $inverse_primary = rgba(984717ff)
  $inverse_surface = rgba(ede0dbff)
  $on_background = rgba(ede0dbff)
  $on_error = rgba(690005ff)
  $on_error_container = rgba(ffdad6ff)
  $on_primary = rgba(562000ff)
  $on_primary_container = rgba(ffdbcbff)
  $on_primary_fixed = rgba(341100ff)
  $on_primary_fixed_variant = rgba(7a3000ff)
  $on_secondary = rgba(432a1eff)
  $on_secondary_container = rgba(ffdbcbff)
  $on_secondary_fixed = rgba(2c160bff)
  $on_secondary_fixed_variant = rgba(5c4033ff)
  $on_surface = rgba(ede0dbff)
  $on_surface_variant = rgba(d7c2b9ff)
  $on_tertiary = rgba(353107ff)
  $on_tertiary_container = rgba(ede4aaff)
  $on_tertiary_fixed = rgba(1f1c00ff)
  $on_tertiary_fixed_variant = rgba(4d481cff)
  $outline = rgba(a08d85ff)
  $outline_variant = rgba(52443dff)
  $primary = rgba(ffb692ff)
  $primary_container = rgba(7a3000ff)
  $primary_fixed = rgba(ffdbcbff)
  $primary_fixed_dim = rgba(ffb692ff)
  $scrim = rgba(000000ff)
  $secondary = rgba(e6beacff)
  $secondary_container = rgba(5c4033ff)
  $secondary_fixed = rgba(ffdbcbff)
  $secondary_fixed_dim = rgba(e6beacff)
  $shadow = rgba(000000ff)
  $surface = rgba(181210ff)
  $surface_bright = rgba(3f3835ff)
  $surface_container = rgba(251e1cff)
  $surface_container_high = rgba(2f2926ff)
  $surface_container_highest = rgba(3a3330ff)
  $surface_container_low = rgba(201a18ff)
  $surface_container_lowest = rgba(120d0bff)
  $surface_dim = rgba(181210ff)
  $surface_tint = rgba(ffb692ff)
  $surface_variant = rgba(52443dff)
  $tertiary = rgba(d0c890ff)
  $tertiary_container = rgba(4d481cff)
  $tertiary_fixed = rgba(ede4aaff)
  $tertiary_fixed_dim = rgba(d0c890ff)
